import { useEffect, useMemo, useState } from "react";
import AdminWorkspaceLayout from "../components/AdminWorkspaceLayout";
import { api } from "../api/client";

export default function AdminTestsPage() {
  const [tests, setTests] = useState([]);
  const [folders, setFolders] = useState([]);
  const [mockFolders, setMockFolders] = useState([]);
  const [current, setCurrent] = useState(null);
  const [name, setName] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = async () => {
    setLoading(true); setError("");
    try {
      const [testsResponse, foldersResponse] = await Promise.all([api.get("/tests/mine"), api.get("/tests/folders")]);
      setTests(Array.isArray(testsResponse.data) ? testsResponse.data : []); setFolders(Array.isArray(foldersResponse.data) ? foldersResponse.data : []);
      try { const { data } = await api.get("/mock-tests"); setMockFolders(Array.isArray(data?.folders) ? data.folders : []); } catch { setMockFolders([]); }
    } catch (err) { setError(err.response?.data?.message || "Could not load admin tests and folders."); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);
  const children = folders.filter((folder) => (folder.parentId ?? null) === (current === "recent" ? null : current));
  const visible = tests.filter((test) => current === "recent" || current == null ? test.folderId == null : test.folderId === current);
  const currentLabel = useMemo(() => current === "recent" ? "Recent tests" : current == null ? "My folders" : folders.find((folder) => folder.id === current)?.name || "Folder", [current, folders]);
  const createFolder = async (event) => { event.preventDefault(); if (!name.trim()) return; try { await api.post("/tests/folders", { name: name.trim(), parentId: current === "recent" || current == null ? null : current }); setName(""); await load(); } catch (err) { setError(err.response?.data?.message || "Could not create folder."); } };
  const moveTest = async (test, folderId) => { try { await api.patch(`/tests/${test.id}/folder`, { folderId: folderId ? Number(folderId) : null }); await load(); } catch (err) { setError(err.response?.data?.message || "Could not move test."); } };
  const addToMock = async (test) => { const choice = window.prompt(`Mock folder ID for “${test.title}” (leave blank for top-level):`, mockFolders[0]?.id || ""); if (choice === null) return; try { await api.post(`/admin/mock-tests/${test.id}/publish`, { folderId: choice ? Number(choice) : null }); await load(); } catch (err) { setError(err.response?.data?.message || "Could not add test to mock library. Run the V18 migration and restart the backend if this endpoint is unavailable."); } };
  const renameFolder = async (folder) => { const next = window.prompt("Folder name", folder.name); if (!next?.trim()) return; try { await api.patch(`/tests/folders/${folder.id}/rename`, { name: next.trim() }); await load(); } catch (err) { setError(err.response?.data?.message || "Could not rename folder."); } };
  const deleteFolder = async (folder) => { if (!window.confirm(`Delete “${folder.name}” and its subfolders?`)) return; try { await api.delete(`/tests/folders/${folder.id}`); setCurrent(null); await load(); } catch (err) { setError(err.response?.data?.message || "Could not delete folder."); } };
  return <AdminWorkspaceLayout title="My Tests"><div className="space-y-5">
    {error && <div className="rounded-xl border border-rose-400/30 bg-rose-500/10 p-3 text-sm text-rose-200">{error}</div>}
    <section className="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-violet-300">Admin test collection</p><h2 className="text-2xl font-bold">{currentLabel}</h2></div><button type="button" onClick={() => setCurrent(null)} className="rounded-xl border border-slate-700 px-3 py-2 text-sm">My folders</button></div><form onSubmit={createFolder} className="mt-4 flex gap-2"><input className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2.5 text-sm" value={name} onChange={(e) => setName(e.target.value)} placeholder={current && current !== "recent" ? "Create subfolder" : "Create folder"} /><button className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold">+ Folder</button></form><div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={() => setCurrent("recent")} className={`rounded-xl border px-3 py-2 text-sm ${current === "recent" ? "border-violet-400 bg-violet-500/20" : "border-slate-700"}`}>📁 Recent tests</button>{folders.filter((folder) => folder.parentId == null).map((folder) => <div key={folder.id} className="flex items-center gap-1"><button type="button" onClick={() => setCurrent(folder.id)} className={`rounded-xl border px-3 py-2 text-sm ${current === folder.id ? "border-violet-400 bg-violet-500/20" : "border-slate-700"}`}>📁 {folder.name}</button><button type="button" onClick={() => renameFolder(folder)} className="rounded-lg px-2 py-2 text-xs text-slate-400 hover:bg-white/10">Rename</button><button type="button" onClick={() => deleteFolder(folder)} className="rounded-lg px-2 py-2 text-xs text-rose-300 hover:bg-rose-500/10">Delete</button></div>)}</div>{current && current !== "recent" && <div className="mt-4 rounded-xl border border-dashed border-slate-700 p-3"><p className="mb-2 text-xs uppercase tracking-wider text-slate-500">Subfolders</p><div className="flex flex-wrap gap-2">{children.map((folder) => <div key={folder.id} className="flex items-center gap-1"><button type="button" onClick={() => setCurrent(folder.id)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs">📁 {folder.name}</button><button type="button" onClick={() => renameFolder(folder)} className="text-xs text-slate-400">Rename</button><button type="button" onClick={() => deleteFolder(folder)} className="text-xs text-rose-300">Delete</button></div>)}{!children.length && <span className="text-xs text-slate-500">No subfolders yet.</span>}</div></div>}</section>
    <section className="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><h2 className="mb-4 text-xl font-bold">Tests in {currentLabel}</h2>{loading ? <p className="py-8 text-center text-sm text-slate-500">Loading tests…</p> : visible.length ? <div className="space-y-3">{visible.map((test) => <article key={test.id} className="flex flex-col gap-3 rounded-xl border border-slate-800 bg-slate-950/50 p-4 lg:flex-row lg:items-center lg:justify-between"><div><h3 className="font-semibold">{test.title}</h3><p className="text-xs text-slate-400">{test.questionCount} questions · {test.isMockTest ? "In mock library" : "Private"}</p></div><div className="flex flex-wrap gap-2"><select aria-label={`Move ${test.title}`} className="rounded-lg border border-slate-700 bg-slate-900 px-2 py-2 text-xs" value={test.folderId || ""} onChange={(e) => moveTest(test, e.target.value)}><option value="">Recent tests</option>{folders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select><button type="button" onClick={() => addToMock(test)} className="rounded-lg bg-violet-600 px-3 py-2 text-xs font-semibold">Add to mock</button></div></article>)}</div> : <p className="py-8 text-center text-sm text-slate-500">No tests in this folder.</p>}</section>
  </div></AdminWorkspaceLayout>;
}
