import { useEffect, useMemo, useState } from "react";
import AdminWorkspaceLayout from "../components/AdminWorkspaceLayout";
import { api } from "../api/client";

export default function AdminContestPage() {
  const [tests, setTests] = useState([]); const [contests, setContests] = useState([]); const [query, setQuery] = useState(""); const [fee, setFee] = useState(5); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [visibleCount, setVisibleCount] = useState(6);
  const load = async () => { const [{ data: testData }, { data: contestData }] = await Promise.all([api.get("/tests/mine"), api.get("/contests/admin")]); setTests(testData || []); setContests(contestData || []); };
  useEffect(() => { load().catch((e) => setError(e.response?.data?.message || "Could not load contests.")); }, []);
  const matches = useMemo(() => tests.filter((test) => test.title.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [tests, query]);
  useEffect(() => { setVisibleCount(6); }, [query]);
  const visibleTests = matches.slice(0, visibleCount);
  const addContest = async (test) => { setBusy(true); setError(""); try { await api.post("/contests/admin", { testId: test.id, entryFeeCoins: Number(fee) }); await load(); } catch (e) { setError(e.response?.data?.message || "Could not add contest."); } finally { setBusy(false); } };
  const removeContest = async (contest) => { if (!window.confirm("Delete this contest? Participant entry fees will be refunded.")) return; setBusy(true); try { await api.delete(`/contests/admin/${contest.id}`); await load(); } catch (e) { setError(e.response?.data?.message || "Could not delete contest."); } finally { setBusy(false); } };
  return <AdminWorkspaceLayout title="Add Contest"><div className="space-y-5">{error && <div className="rounded-xl bg-rose-500/10 p-3 text-sm text-rose-200">{error}</div>}<section className="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><h2 className="text-xl font-bold">Choose a test</h2><p className="mt-1 text-sm text-slate-400">Search your generated tests, then add one as the weekly contest.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input className="flex-1 rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2.5" placeholder="Search test name..." value={query} onChange={(e) => setQuery(e.target.value)} /><input type="number" min="0" className="w-full rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2.5 sm:w-32" value={fee} onChange={(e) => setFee(e.target.value)} aria-label="Entry fee" /></div><div className="mt-4 space-y-2">{visibleTests.map((test) => <div key={test.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-950/50 p-3"><div><p className="font-semibold">{test.title}</p><p className="text-xs text-slate-400">{test.questionCount} questions · Entry {fee} coins</p></div><button type="button" disabled={busy} onClick={() => addContest(test)} className="rounded-lg bg-violet-600 px-3 py-2 text-sm font-semibold disabled:opacity-50">Add as contest</button></div>)}{!matches.length && <p className="py-5 text-center text-sm text-slate-500">No matching generated tests.</p>}{visibleCount < matches.length && <button type="button" className="mx-auto mt-3 block rounded-lg border border-violet-400/40 px-4 py-2 text-sm text-violet-200" onClick={() => setVisibleCount((count) => count + 6)}>Show more tests</button>}</div></section><section className="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><h2 className="text-xl font-bold">Scheduled contests</h2><div className="mt-4 space-y-2">{contests.map((contest) => <div key={contest.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-950/50 p-3"><div><p className="font-semibold">Contest #{contest.id}</p><p className="text-xs text-slate-400">{contest.scheduledDate} · {contest.status} · {contest.entryFeeCoins} coins</p></div><button type="button" disabled={busy} onClick={() => removeContest(contest)} className="rounded-lg border border-rose-400/40 px-3 py-2 text-sm text-rose-200">Delete contest</button></div>)}{!contests.length && <p className="py-5 text-center text-sm text-slate-500">No scheduled contests.</p>}</div></section></div></AdminWorkspaceLayout>;
}
