import { useEffect } from "react";

// Replace these starter quotes with the full set of 31 supplied by the user.
export const ADDITIONAL_MOTIVATIONAL_QUOTES = [
  "Small steps lead to big achievements.",
  "Your future is built by today's efforts.",
  "Every page you read brings you closer.",
  "Consistency beats temporary motivation.",
  "Dream big, study smart, act daily.",
  "Your effort today is your strength tomorrow.",
  "Progress matters more than perfection.",
  "Make every study session count.",
  "Success begins when excuses end.",
  "Believe in the power of preparation.",
  "A focused mind can achieve great things.",
  "Learn something new every single day.",
  "Your dedication will shape your future.",
  "Great results come from steady effort.",
  "Keep learning, keep growing, keep going.",
  "Turn your goals into daily habits.",
  "Every mistake is a lesson in disguise.",
  "Discipline carries you beyond motivation.",
  "Your hard work is never wasted.",
  "Start where you are and keep moving.",
  "The journey becomes easier with practice.",
  "Challenge yourself to improve every day.",
  "Knowledge is an investment in yourself.",
  "A little progress is still progress.",
  "Stay patient with your learning journey.",
  "Your dreams deserve your daily effort.",
  "Focus on what you can improve today.",
  "Be stronger than your excuses.",
  "Every chapter brings new possibilities.",
  "Study with purpose, not just pressure.",
  "Build habits that support your ambitions.",
  "Let your actions reflect your goals.",
  "Your potential grows with practice.",
  "One focused hour can change your day.",
  "Success is built one decision at a time.",
  "Keep showing up for your future.",
  "Your dedication makes a difference.",
  "Turn difficult lessons into lasting knowledge.",
  "Trust the process and do the work.",
  "Make today's effort count tomorrow.",
  "You are capable of learning difficult things.",
  "Every question is an opportunity to grow.",
  "The best time to begin is now.",
  "Your progress is worth celebrating.",
  "Stay curious and keep discovering.",
  "Effort creates opportunities.",
  "A clear goal gives effort direction.",
  "Your future self will thank you.",
  "Learn patiently and practice consistently.",
  "Small improvements create lasting change.",
  "Be committed to becoming better.",
  "Every day offers a fresh beginning.",
  "Your mindset shapes your progress.",
  "Prepare today to feel confident tomorrow.",
  "Success starts with a single step.",
  "Keep your goals bigger than your doubts.",
  "Make learning a lifelong habit.",
  "Hard work turns potential into achievement.",
  "A strong routine builds a strong future.",
  "Your determination is your advantage.",
  "Focus on growth, not comparison.",
  "Keep going, even when progress feels slow.",
  "Every effort adds to your experience.",
  "Turn your ambition into action.",
  "Your study habits shape your results.",
  "Learn from yesterday and improve today.",
  "Be consistent when nobody is watching.",
  "Your goals are worth the effort.",
  "Stay focused on what truly matters.",
  "Practice until confidence becomes natural.",
  "You grow every time you try.",
  "Let persistence become your superpower.",
  "Build your future through daily learning.",
  "A determined learner finds a way.",
  "Your best investment is your education.",
  "Keep moving toward meaningful goals.",
  "Success rewards preparation and persistence.",
  "Every study session is a fresh opportunity.",
  "Be proud of your honest effort.",
  "Choose progress over procrastination.",
  "Your dreams need your discipline.",
  "Learn today, lead tomorrow.",
  "A focused beginning creates momentum.",
  "Turn your challenges into learning opportunities.",
  "Keep your curiosity alive.",
  "Your effort can change your direction.",
  "One more attempt can make the difference.",
  "Make room for growth every day.",
  "Study with patience and purpose.",
  "The work you do matters.",
  "Keep building your skills quietly.",
  "Believe in improvement through practice.",
  "Let consistency become your identity.",
  "Your goals deserve focused attention.",
  "A better future starts with today's choices.",
  "Never underestimate a steady learner.",
  "Each lesson adds to your strength.",
  "Stay determined when things get difficult.",
  "Make your time work for your dreams.",
  "Keep learning beyond the classroom.",
  "Progress begins with a willing mind.",
  "Your effort is shaping your story.",
  "Turn knowledge into confidence.",
  "Be persistent, especially on difficult days.",
  "A strong foundation supports great achievements.",
  "Keep your attention on the next step.",
  "Your commitment creates momentum.",
  "Every page is progress.",
  "Small victories build lasting confidence.",
  "Let your goals guide your choices.",
  "Work steadily toward your ambitions.",
  "Your learning journey is uniquely yours.",
  "Be patient with yourself and persistent with your goals.",
  "Success grows from repeated effort.",
  "Focus deeply and learn meaningfully.",
  "Your future is worth preparing for.",
  "Make every opportunity to learn count.",
  "A little discipline goes a long way.",
  "Keep turning effort into improvement.",
  "Your habits are shaping your destiny.",
  "Learn with intention and act with confidence.",
  "Every difficult topic can be understood.",
  "Stay committed to your progress.",
  "The next step is always available.",
  "Use your time to build something valuable.",
  "Your dedication will open new doors.",
  "Keep your standards high and your effort steady.",
  "Learning is progress you can carry anywhere.",
  "A calm mind learns more effectively.",
  "Practice makes unfamiliar things manageable.",
  "Your consistency is creating change.",
  "Every goal begins with a decision.",
  "Choose to improve a little each day.",
  "Be willing to learn, unlearn, and grow.",
  "Your potential deserves patience.",
  "Keep working toward the person you want to become.",
  "Today's discipline creates tomorrow's options.",
  "Let every setback teach you something useful.",
  "Your effort gives your dreams a foundation.",
  "Study with focus and finish with pride.",
  "Make progress your daily priority.",
  "The smallest action can begin a breakthrough.",
  "Keep your purpose close.",
  "Your determination can outlast difficulty.",
  "Build confidence through preparation.",
  "Every answer begins with a question.",
  "Keep investing in your knowledge.",
  "You can improve with every attempt.",
  "Let curiosity lead your learning.",
  "Your patience is part of your progress.",
  "Be consistent before seeking perfection.",
  "Make today's work tomorrow's advantage.",
  "Your goals become clearer through action.",
  "A strong learner keeps asking why.",
  "Keep showing up, even for small tasks.",
  "Your effort today creates future choices.",
  "Turn your free time into growth.",
  "Keep your focus stronger than distractions.",
  "Every lesson has something to teach you.",
  "Learn at your pace, but keep moving.",
  "Your commitment is building your confidence.",
  "A productive day begins with a clear plan.",
  "Take the first step before you feel ready.",
  "Keep your ambitions alive through action.",
  "Your discipline is a gift to your future.",
  "The path to mastery starts with practice.",
  "Every challenge can strengthen your skills.",
  "Be curious enough to keep exploring.",
  "Keep improving, one decision at a time.",
  "Your progress deserves patience and respect.",
  "Small efforts accumulate into big results.",
  "Choose learning over hesitation.",
  "Let your preparation speak for itself.",
  "A focused learner keeps finding possibilities.",
  "Make your goals part of your routine.",
  "Keep building knowledge brick by brick.",
  "Your future grows from what you practice.",
  "Work on your goals even when motivation fades.",
  "A new day brings another chance to improve.",
  "Your effort is an investment, not a loss.",
  "Stay open to feedback and improvement.",
  "Be brave enough to begin again.",
  "Learning turns uncertainty into understanding.",
  "Keep your attention on meaningful progress.",
  "Your persistence is building resilience.",
  "Make your next action a useful one.",
  "The work gets easier as your skills grow.",
  "Keep learning until confidence follows.",
  "Your dreams need action more than wishes.",
  "Be intentional with every study session.",
  "Your best work begins with focused effort.",
  "Let every day move you forward.",
  "Stay steady when the journey feels long.",
  "Your knowledge grows with every revision.",
  "Keep your priorities clear.",
  "A determined mind keeps searching for solutions.",
  "Make time for the future you want.",
  "Your effort is proof of your commitment.",
  "Every revision strengthens your understanding.",
  "Learn from the process, not only the result.",
  "Your consistency creates dependable progress.",
  "Keep practicing what you want to master.",
  "Let your curiosity outgrow your fear.",
  "One goal, one step, one day at a time.",
  "You can begin again without starting from zero.",
  "Build the confidence that comes from preparation.",
  "Your education expands your possibilities.",
  "Keep turning questions into knowledge.",
  "Be disciplined with your time and kind to yourself.",
  "The next breakthrough may come from practice.",
  "Keep your goals visible and your actions consistent.",
  "A strong work ethic creates lasting value.",
  "Your learning today supports your success tomorrow.",
  "Every attempt brings useful experience.",
  "Keep making choices your future self will appreciate.",
  "Your effort can make hard things manageable.",
  "Stay focused on what you are becoming.",
  "The habit of learning is a lifelong advantage.",
  "Your goals deserve more than occasional effort.",
  "Keep moving, even if the steps are small.",
  "Preparation turns opportunity into possibility.",
  "Be consistent enough to see the difference.",
  "Every day is a chance to strengthen your skills.",
  "Your progress is built through repetition.",
  "Learn deeply, remember clearly, apply confidently.",
  "Keep your mind open and your effort steady.",
  "Your next achievement starts with today's practice.",
  "A purposeful routine makes progress easier.",
  "Be committed to the work behind the dream.",
  "Every new skill begins with being a beginner.",
  "Let your effort be greater than your hesitation.",
  "You are building more than marks; you are building skills.",
  "Keep investing in the person you are becoming.",
  "A focused mind can make meaningful progress.",
  "Your daily choices are shaping your future.",
  "Keep going until your effort becomes experience.",
  "Be willing to work for what matters.",
  "Every topic mastered expands your confidence.",
  "Your determination gives your goals momentum.",
  "Make learning a priority, not an afterthought.",
  "Keep your progress moving in the right direction.",
  "The courage to try is a form of strength.",
  "A good question can open a new path.",
  "Keep improving the skills that matter to you.",
  "Your patience will support your persistence.",
  "Learn consistently and trust your preparation.",
  "A clear plan turns intention into action.",
  "Your goals become achievable through daily work.",
  "Every focused minute has value.",
  "Keep your energy directed toward growth.",
  "You can learn more than you currently know.",
  "Practice today what you want to do confidently tomorrow.",
  "Your effort is laying the groundwork for success.",
  "Keep your ambition practical and your vision bold.",
  "A strong future is built through small decisions.",
  "Learn from your mistakes without living in them.",
  "Your commitment matters on ordinary days.",
  "Keep turning your plans into completed tasks.",
  "Every study session strengthens your discipline.",
  "Your future is shaped by repeated choices.",
  "Stay curious about how things work.",
  "The effort you repeat becomes a skill.",
  "Keep your goals meaningful and your steps realistic.",
  "Your growth is worth the patience it requires.",
  "Make each day a little more intentional.",
  "A learner's greatest tool is curiosity.",
  "Keep working until the concept becomes clear.",
  "Your progress is bigger than one difficult day.",
  "Choose a steady pace you can sustain.",
  "Every new attempt gives you another chance.",
  "Build your future with focused moments.",
  "Keep practicing, even when improvement is subtle.",
  "Your discipline makes room for opportunity.",
  "Be persistent with the process and flexible with the plan.",
  "Let your learning compound over time.",
  "You can turn confusion into clarity through practice.",
  "Keep your goals ahead of your distractions.",
  "The strongest progress often happens quietly.",
  "Your effort today is part of a bigger picture.",
  "Make each revision count.",
  "Keep developing the skills your future requires.",
  "A difficult beginning can lead to strong understanding.",
  "Your next step does not need to be perfect.",
  "Keep learning with patience and purpose.",
  "The decision to continue is powerful.",
  "Your habits are stronger when repeated.",
  "Be proud of the work nobody sees.",
  "Every day of practice adds experience.",
  "Keep your mind focused on possibilities.",
  "Your learning can open unexpected doors.",
  "Build momentum by starting small.",
  "Stay committed to your own improvement.",
  "A little effort every day creates a strong foundation.",
  "Keep your goals connected to your daily actions.",
  "Your ability grows when you challenge it.",
  "Learning is a journey of continuous improvement.",
  "Every setback can inform your next attempt.",
  "Make progress visible by tracking your effort.",
  "Your persistence gives your talent room to grow.",
  "Keep building the future one habit at a time.",
  "Be consistent with the promises you make yourself.",
  "Your curiosity is the beginning of discovery.",
  "Focus on understanding, not just memorizing.",
  "Keep choosing the work that moves you forward.",
  "A prepared mind meets challenges with confidence.",
  "Your progress deserves recognition.",
  "Make your study time purposeful.",
  "Every solved problem strengthens your reasoning.",
  "Keep your determination steady through uncertainty.",
  "Your effort creates options you do not yet see.",
  "Learn something today that your future can use.",
  "Small actions make ambitious goals approachable.",
  "Keep building skills that last.",
  "Your focus is a resource worth protecting.",
  "The road to improvement is made of practice.",
  "Be patient with the results and consistent with the effort.",
  "Keep your learning active and your mind curious.",
  "Today's practice becomes tomorrow's ability.",
  "Your next success begins with preparation.",
  "Keep moving toward your goals with intention.",
  "A thoughtful learner keeps getting better.",
  "Every chapter completed is progress earned.",
  "Let your daily routine support your biggest goals.",
  "Your effort has value beyond the outcome.",
  "Keep working through the parts you do not understand yet.",
  "You become more capable by continuing to learn.",
  "Stay focused on the next useful action.",
  "Your goals deserve a place on your calendar.",
  "Make steady effort your competitive advantage.",
  "Keep your confidence rooted in preparation.",
  "Every day of learning adds to your foundation.",
  "Be willing to struggle while learning something new.",
  "Your progress is built, not wished into existence.",
  "Keep showing yourself what consistency can do.",
  "A small start can lead to a meaningful finish.",
  "Your ability to improve is always worth developing.",
  "Let each challenge sharpen your approach.",
  "Keep your attention on effort you can control.",
  "Your future benefits from today's discipline.",
  "Practice transforms knowledge into usable skill.",
  "Keep building confidence one lesson at a time.",
  "Your goals are worth protecting from distractions.",
  "Learn patiently, revise regularly, and keep progressing.",
  "Every meaningful achievement begins with effort.",
  "Your consistency is more important than a perfect start.",
  "Keep creating opportunities through learning.",
  "A focused routine makes difficult goals manageable.",
  "Your next improvement begins with honest reflection.",
  "Keep making time for what matters.",
  "Learning is progress that stays with you.",
  "Be determined enough to try another approach.",
  "Your effort can outlast a temporary setback.",
  "Keep your study goals specific and achievable.",
  "Each practice session builds familiarity.",
  "Your dedication gives your ambitions direction.",
  "Take pride in becoming more capable.",
  "Keep learning even when the answer is not immediate.",
  "Your future is a reason to begin today.",
  "Every day of discipline strengthens your foundation.",
  "Turn your attention into meaningful work.",
  "Keep your goals close and your distractions distant.",
  "Your improvement is worth the repetition.",
  "A little more understanding is a real achievement.",
  "Keep going until today's challenge becomes tomorrow's skill.",
  "Your effort is creating lasting value.",
  "Be consistent enough to trust your own progress.",
  "Every new concept expands your perspective.",
  "Keep making learning part of your everyday life.",
  "Your willingness to improve is a strength.",
  "Build your future with patience and action.",
  "Every focused session is a promise kept.",
  "Keep your learning goals alive through practice.",
  "Your progress is made one decision at a time.",
  "Be curious, be patient, and keep working.",
  "Today's effort is tomorrow's foundation.",
  "Keep investing attention where it matters most.",
  "You can make progress without feeling motivated.",
  "Your discipline helps turn plans into results.",
  "Every revision is another chance to understand.",
  "Keep your mind open to better methods.",
  "Your goals become real through repeated action.",
  "A strong learner knows when to ask for help.",
  "Keep moving forward with what you know.",
  "Your next step can be simple and meaningful.",
  "Every problem is practice for your thinking.",
  "Stay committed to learning, not just finishing.",
  "Your effort is building future confidence.",
  "Keep making your knowledge more useful.",
  "A productive habit begins with repetition.",
  "Your progress does not need to look like anyone else's.",
  "Keep practicing until the basics feel natural.",
  "Every day offers another chance to grow.",
  "Your patience helps difficult ideas become clear.",
  "Make your actions match your ambitions.",
  "Keep choosing progress, even in small amounts.",
  "Your work today supports your goals tomorrow.",
  "A learning mindset turns obstacles into questions.",
  "Keep your study routine realistic and consistent.",
  "Your effort is helping you become more capable.",
  "Every skill you build expands your choices.",
  "Keep going; your practice is adding up.",
  "Your future deserves thoughtful preparation.",
  "Be persistent with the goal and patient with yourself.",
  "A clear purpose makes effort more meaningful.",
  "Keep learning beyond what is required.",
  "Your progress is worth the work.",
  "Small steps are still steps toward success.",
  "Make your next hour count.",
  "Keep building a habit of finishing what you start.",
  "Your determination can carry you through uncertainty.",
  "Every lesson learned becomes part of your toolkit.",
  "Keep your focus on growth you can sustain.",
  "Your effort today is shaping tomorrow's confidence.",
  "Be brave enough to ask difficult questions.",
  "Keep working toward meaningful mastery.",
  "Your learning journey is full of new possibilities.",
  "A focused effort is better than scattered activity.",
  "Keep your promises to your goals.",
  "Your skills grow when you use them.",
  "Every practice question is a chance to improve.",
  "Keep moving forward with patience.",
  "Your future is worth today's concentration.",
  "Be consistent in the work that matters.",
  "A new approach can unlock a difficult concept.",
  "Keep your curiosity stronger than your frustration.",
  "Your dedication is creating progress.",
  "Every day you practice, you build familiarity.",
  "Keep improving your process, not just your results.",
  "Your goals are reached through ordinary daily effort.",
  "Make learning an active choice.",
  "Keep your ambition supported by a plan.",
  "Your next achievement begins with a small action.",
  "Stay patient, stay focused, stay in motion.",
  "Every attempt teaches you how to improve.",
  "Your effort is part of your growth.",
  "Keep developing the mindset of a lifelong learner.",
  "A strong routine can carry you through low motivation.",
  "Your progress begins where procrastination ends.",
  "Keep learning until you can explain it clearly.",
  "Your focus today creates possibilities tomorrow.",
  "Every moment of practice has a purpose.",
  "Be willing to improve one detail at a time.",
  "Keep your goals realistic and your effort sincere.",
  "Your knowledge grows when you revisit it.",
  "Make persistence part of your daily routine.",
  "Keep building skills that serve your future.",
  "Your learning can be difficult and worthwhile.",
  "Every completed task builds momentum.",
  "Stay dedicated to the process of getting better.",
  "Your next chapter begins with what you do today.",
  "Keep taking action while you keep learning.",
  "Your discipline is helping your dreams take shape.",
  "A patient learner can master complex ideas.",
  "Keep making progress you can be proud of.",
  "Every day of effort moves the needle.",
  "Your future is built through consistent preparation.",
  "Keep turning your attention into achievement.",
  "Your willingness to practice is a powerful asset.",
  "Make the effort today that tomorrow will need.",
  "Keep your mind engaged and your goals clear.",
  "Every challenge is a chance to develop a skill.",
  "Your daily effort is building lasting confidence.",
  "Keep choosing habits that help you grow.",
  "A thoughtful plan makes focused work easier.",
  "Your learning is valuable at every stage.",
  "Keep going, even when the results take time.",
  "Your commitment is stronger when it becomes routine.",
  "Every question you explore expands your understanding.",
  "Keep your effort steady and your expectations realistic.",
  "Your progress is built through patience and practice.",
  "Make each day an opportunity to learn.",
  "Keep developing the skills that support your dreams.",
  "Your next step matters more than perfect timing.",
  "Every revision brings another chance for clarity.",
  "Stay focused on what you can do right now.",
  "Your effort is preparing you for future opportunities.",
  "Keep making small improvements that last.",
  "A curious mind finds lessons everywhere.",
  "Your persistence makes progress possible.",
  "Keep practicing the things that challenge you.",
  "Your study routine is an investment in yourself.",
  "Every small win strengthens your momentum.",
  "Keep learning with courage and consistency.",
  "Your goals become manageable when broken into steps.",
  "Be focused on progress and honest about effort.",
  "Every difficult lesson can become familiar.",
  "Keep building your confidence through action.",
  "Your future can benefit from one good habit.",
  "Make room for practice in your daily schedule.",
  "Keep working with purpose, even on ordinary days.",
  "Your knowledge is built one idea at a time.",
  "Every day is another chance to do meaningful work.",
  "Keep your effort aligned with your priorities.",
  "Your growth is happening every time you practice.",
  "Be patient enough to learn things properly.",
  "Keep making your future a daily priority.",
  "Every focused choice supports your goals.",
  "Your effort is creating a stronger foundation.",
  "Keep learning from people, books, and experience.",
  "A steady learner keeps finding ways forward.",
  "Your dedication is worth the time it takes.",
  "Every new attempt can improve your understanding.",
  "Keep your progress moving, however slowly.",
  "Your goals deserve consistent attention.",
  "Build your confidence by keeping your commitments.",
  "Every study day adds to your experience.",
  "Keep working toward clarity, not just completion.",
  "Your effort today is a step toward independence.",
  "A focused mind turns time into progress.",
  "Keep improving the way you learn.",
  "Your future options grow with your skills.",
  "Every bit of practice makes a contribution.",
  "Stay committed to your own learning path.",
  "Your determination is built through repeated choices.",
  "Keep making the effort that your goals require.",
  "A strong learner values progress over pride.",
  "Your next breakthrough starts with persistence.",
  "Every day you continue, you strengthen your habits.",
  "Keep your goals meaningful and your effort practical.",
  "Your study journey is an opportunity to grow.",
  "Make consistent effort your daily standard.",
  "Keep learning, even when progress is hard to measure.",
  "Your patience today supports your success tomorrow.",
  "Every small action helps build a larger result.",
  "Keep showing up with a willingness to improve.",
  "Your future self is shaped by today's habits.",
  "Stay curious, stay disciplined, and keep moving.",
  "Your effort is turning possibility into progress.",
  "Every lesson is another tool for your future.",
  "Keep your attention on what you can influence.",
  "Your goals are worth a focused beginning.",
  "Make learning a habit you can rely on.",
  "Keep practicing until your understanding feels solid.",
  "Your progress is proof that effort adds up.",
  "Every day gives you a chance to start well.",
  "Keep building knowledge that you can apply.",
  "Your commitment makes difficult goals approachable.",
  "A little focus can transform an ordinary session.",
  "Keep moving toward the future you imagine.",
  "Your growth is worth consistent effort.",
  "Every attempt is part of becoming more skilled.",
  "Keep your motivation alive through meaningful action.",
  "Your learning today creates choices for tomorrow.",
  "Be persistent, even when the path changes.",
  "Every completed lesson is progress you earned.",
  "Keep your study goals connected to your purpose.",
  "Your effort can make tomorrow easier.",
  "A strong learner keeps adapting.",
  "Keep working with patience and confidence.",
  "Your dedication is building something lasting.",
  "Every minute spent learning can add value.",
  "Keep choosing the next step over standing still.",
  "Your progress is a reason to continue.",
  "Learn with focus, practice with purpose, grow with patience.",
  "Keep making your effort count.",
  "Your future begins with the habits you build today.",
  "Every small step is part of a bigger journey.",
  "Keep learning and let your skills speak.",
  "Your consistency is creating opportunities.",
  "A focused day can move you closer to your goals.",
  "Keep growing into your own potential.",
  "Your effort is worth repeating.",
  "Every challenge can teach you a better method.",
  "Keep your determination steady and your mind open.",
  "Your learning journey is worth showing up for.",
  "Make today a useful part of your progress.",
  "Keep building the habits that build you.",
  "Your future is strengthened by what you learn.",
  "Every attempt is a chance to become more capable.",
  "Keep practicing with patience and intention.",
  "Your progress starts with the choice to continue.",
  "Let your daily effort tell your story.",
  "Keep learning; your possibilities are still growing.",
  "Your goals are closer with every focused step.",
  "Make your effort consistent and your purpose clear.",
  "Keep moving forward, one lesson at a time.",
  "Your next success begins with today's commitment.",
  "Every day of learning is a step toward growth.",
  "Keep your focus on becoming better.",
  "Your future is worth the work you put in today.",
  "Be consistent, stay curious, and trust your progress.",
  "Keep going; every effort contributes to your journey.",
  "Your dedication today is an investment in tomorrow.",
  "Every new lesson gives you another opportunity.",
  "Keep building a future you can be proud of.",
  "Your progress is made through patience, practice, and persistence.",
  "Start small, stay steady, and keep growing.",
  "The work you do today gives tomorrow a head start.",
  "Keep learning, because your potential is still unfolding.",
  "Your effort matters, even when nobody notices.",
  "One focused step is better than another day of waiting.",
  "Keep practicing; improvement follows attention and effort.",
  "Your goals deserve your best available effort today.",
  "Make every lesson a chance to move forward.",
  "Keep building your future with the choices you make now.",
  "Stay focused, stay consistent, and keep believing in growth.",
  "Your next achievement begins with the work in front of you.",
  "Every day you learn, you expand what is possible.",
  "Keep going; you are building something meaningful."
];

export default function MotivationalQuoteModal({ open, quoteIndex, onClose, onNext }) {
  useEffect(() => {
    if (!open) return undefined;
    const handleKeyDown = (event) => {
      if (event.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [open, onClose]);

  if (!open) return null;
  const quote = MOTIVATIONAL_QUOTES[quoteIndex];

  return (
    <div className="quote-overlay" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
      <section className="quote-card" role="dialog" aria-modal="true" aria-labelledby="quote-title">
        <button className="quote-close" onClick={onClose} aria-label="Close quote">×</button>
        <div className="quote-sparkle" aria-hidden="true">✦</div>
        <span className="quote-eyebrow" id="quote-title">A LITTLE MOTIVATION</span>
        <blockquote key={quoteIndex} className="quote-text">“{quote}”</blockquote>
        <div className="quote-author">— AptiGen</div>
        <button className="quote-next" onClick={onNext}>Another quote <span>→</span></button>
      </section>
      <style>{`
        .quote-overlay{position:fixed;inset:0;z-index:100;display:grid;place-items:center;padding:1.25rem;background:rgba(5,8,25,.68);backdrop-filter:blur(9px);animation:quote-fade-in .22s ease both}
        .quote-card{position:relative;isolation:isolate;overflow:hidden;width:min(100%,480px);padding:2.5rem 2.2rem 1.8rem;text-align:center;border:1px solid rgba(167,112,255,.65);border-radius:26px;color:#f7f4ff;background:radial-gradient(ellipse at 50% -20%,rgba(112,60,255,.36),transparent 62%),linear-gradient(145deg,#151936,#0c122b);box-shadow:0 25px 90px rgba(0,0,0,.45),0 0 42px rgba(133,68,255,.25);animation:quote-card-enter .55s cubic-bezier(.18,.85,.25,1) both}
        .quote-card:before{content:"";position:absolute;inset:10px;border:1px solid rgba(164,132,255,.11);border-radius:19px;pointer-events:none;z-index:-1}
        .quote-close{position:absolute;top:.8rem;right:1rem;width:36px;height:36px;border:1px solid rgba(192,181,255,.2);border-radius:50%;background:rgba(255,255,255,.05);color:#e3ddff;font-size:1.5rem;line-height:1;cursor:pointer}
        .quote-sparkle{font-size:2rem;color:#d79cff;text-shadow:0 0 22px #a65cff;animation:quote-sparkle 2s ease-in-out infinite}
        .quote-eyebrow{display:block;margin-top:.45rem;color:#bd93ff;font-size:.7rem;font-weight:800;letter-spacing:.2em}
        .quote-text{margin:1.25rem 0 .75rem;font-family:'Sora',sans-serif;font-size:clamp(1.45rem,5vw,2.2rem);font-weight:750;line-height:1.3;letter-spacing:-.035em;background:linear-gradient(100deg,#fff,#d5b2ff 55%,#ffb5e5);background-clip:text;-webkit-background-clip:text;color:transparent;animation:quote-text-enter .45s cubic-bezier(.2,.8,.2,1) both}
        .quote-author{color:#aab4dc;font-size:.86rem}
        .quote-next{display:inline-flex;align-items:center;gap:.6rem;margin-top:1.8rem;padding:.7rem 1.1rem;border:1px solid rgba(164,112,255,.56);border-radius:999px;background:linear-gradient(100deg,rgba(110,61,239,.9),rgba(177,45,224,.9));color:#fff;font-weight:700;box-shadow:0 5px 22px rgba(119,54,231,.3);cursor:pointer;transition:transform .2s,box-shadow .2s}
        .quote-next:hover{transform:translateY(-2px);box-shadow:0 9px 27px rgba(119,54,231,.42)}
        @keyframes quote-fade-in{from{opacity:0}to{opacity:1}}
        @keyframes quote-card-enter{from{opacity:0;transform:translateY(22px) scale(.92)}65%{transform:translateY(-3px) scale(1.015)}to{opacity:1;transform:translateY(0) scale(1)}}
        @keyframes quote-text-enter{from{opacity:0;transform:translateY(12px);filter:blur(5px)}to{opacity:1;transform:translateY(0);filter:blur(0)}}
        @keyframes quote-sparkle{0%,100%{transform:scale(.92) rotate(-8deg);opacity:.75}50%{transform:scale(1.12) rotate(8deg);opacity:1}}
        [data-theme="aptigen"] .quote-card{color:#222949;background:radial-gradient(ellipse at 50% -20%,rgba(112,60,255,.15),transparent 62%),linear-gradient(145deg,#fff,#f5f1ff);box-shadow:0 25px 80px rgba(34,36,80,.22),0 0 35px rgba(133,68,255,.17)}
        [data-theme="aptigen"] .quote-author{color:#687391}
        [data-theme="aptigen"] .quote-close{color:#50347b;background:#f4efff;border-color:#ded1f5}
        @media(prefers-reduced-motion:reduce){.quote-overlay,.quote-card,.quote-text,.quote-sparkle{animation:none!important}.quote-next{transition:none}}
      `}</style>
    </div>
  );
}
